### ISSUE TITLE
(BUG) The application crashes when I try to open the application

### ISSUE THREAD

**Issue by friendsmobile** [lyjacky11/TimeSheetsApp#1]
# Project Information

* Repository: https://github.com/lyjacky11/TimeSheetsApp
* Project Name: TimeSheetsApp
* My Github Account: https://github.com/friendsmobile
* Download the application: [Here](https://github.com/lyjacky11/TimeSheetsApp/releases)

# Expected behavior

When I try to open the application, then the application should be opened. so that Users can easily access all options

# Actual behavior

The application crashes when I try to open the application

# How to reproduce

* After installing the application, try opening it
* Note the Error

* Browser/App version:  v1.3
* Operating system: 6.0

# Recording Of The Bug

![20190609_170140](https://user-images.githubusercontent.com/51118734/59158754-eaff9000-8a73-11e9-9974-05ced3b7061f.gif)

# Logcat

<pre><code>D/AndroidRuntime(25085): Shutting down VM

E/AndroidRuntime(25085): FATAL EXCEPTION: main

E/AndroidRuntime(25085): Process: com.lyjacky11.timesheet, PID: 25085

E/AndroidRuntime(25085): android.content.res.Resources$NotFoundException: Resource ID #0x7f070068

E/AndroidRuntime(25085): 	at android.content.res.Resources.getValue(Resources.java:1542)

E/AndroidRuntime(25085): 	at a.b.h.g.p.e(:4)

E/AndroidRuntime(25085): 	at a.b.h.g.p.a(:9)

E/AndroidRuntime(25085): 	at a.b.h.g.p.c()

E/AndroidRuntime(25085): 	at a.b.h.c.a.a.c()

E/AndroidRuntime(25085): 	at a.b.h.f.a.p.getIcon(:2)

E/AndroidRuntime(25085): 	at android.support.v7.view.menu.ActionMenuItemView.a()

E/AndroidRuntime(25085): 	at a.b.h.g.g.a(:17)

E/AndroidRuntime(25085): 	at a.b.h.g.g.a(:12)

E/AndroidRuntime(25085): 	at a.b.h.f.a.l.a()

E/AndroidRuntime(25085): 	at a.b.h.g.g.a(:43)

E/AndroidRuntime(25085): 	at a.b.h.f.a.l.b(:1)

E/AndroidRuntime(25085): 	at a.b.h.f.a.l.h()

E/AndroidRuntime(25085): 	at a.b.h.a.x.b(:6)

E/AndroidRuntime(25085): 	at a.b.h.a.x.c(:2)

E/AndroidRuntime(25085): 	at a.b.h.a.q.run()

E/AndroidRuntime(25085): 	at android.os.Handler.handleCallback(Handler.java:739)

E/AndroidRuntime(25085): 	at android.os.Handler.dispatchMessage(Handler.java:95)

E/AndroidRuntime(25085): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(25085): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime(25085): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(25085): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(25085): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime(25085): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
</code></pre>

**Comment by lyjacky11** [comment]
Seems like it's unable to load some of the layout resources, looking for a solution

**Comment by lyjacky11** [comment]
Unfortunately, I can't reproduce this bug on my device, might be an Android 6.0 issue. I only have an Android 9.0 device available for testing. I don't know how to fix this bug, let me know if you find any solutions!
