### ISSUE TITLE
Pull Down to Refresh

### ISSUE THREAD

**Issue by trevor-clarke** [lyjacky11/TimeSheetsApp#2]
## Expected Behavior
When you move your finger on the app, data shouldn't disappear.

## Current Behavior
The app seems to refresh?

## Possible Solution
Disable the swipe down to refresh.

## Steps to Reproduce
1. Open the app.
2. Use the swipe down to refresh gesture.
3. Lose the data entered in the form.

## Context (Environment)

It makes it feel as though I am going to lose the data I have entered.

**Comment by lyjacky11** [comment]
Thanks for the feedback! Will implement a fix in the next update.

**Comment by lyjacky11** [comment]
Added a message at the top of the app indicating that swiping down will refresh the page.

See commit: 1c2dcbc2b59f6d3a9332919aea13f60dfdc564a6 in file: [app/src/main/assets/index.html](https://github.com/lyjacky11/TimeSheetsApp/blob/master/app/src/main/assets/index.html)
